### ISSUE TITLE
Simple Refactoring Proposal for emmy Client

### ISSUE THREAD

**Issue by miha-plesko** [xlab-si/emmy#3]
Currently emmy Client is implemented as follows:
```go
type Client struct {
    id      int32
    conn    *grpc.ClientConn
    client  *pb.ProtocolClient
    stream  pb.Protocol_RunClient
    schema  pb.SchemaType // int32
    variant pb.SchemaVariant
    handler *ClientHandler
}

func (c *Client) Pedersen(dlog *dlog.ZpDLog, val big.Int) error {
    c.handler.pedersenCommitter = commitments.NewPedersenCommitter(dlog)
    ... // c.handler.pedersenCommitter is used
}

func (c *Client) Schnorr(protocolType common.ProtocolType, dlog *dlog.ZpDLog, secret big.Int) error {
    c.handler.schnorrProver = dlogproofs.NewSchnorrProver(dlog, protocolType)
    ... // c.handler.schnorrProver is used
}
```

So example has to be started like this:
```go
genClient := getGenericClient(endpoint, example)
genClient.ExecuteProtocol(protocolParams)  // decides whether c.Pedersen() whether c.Schnorr() is run
```
What bothers me is that such an approach is hard to read. Also, when adding support for new schema, one has to modify everything: the Client struct (hook additional function), the ClientHandler struct (store additional Commiter) and the ExecuteProtocol() function (additional case).

# Proposed change
What if Client was an interface:
```go
type Client interface{
    ExecuteProtocol()
}
```
and we implement it for each schema we provide:
```go
type PedersenClient struct{}

func (c *PedersenClient) ExecuteProtocol(){
    // bouncing protocol is run
}
```
```go
type SchnorrClient struct{}

func (c *SchnorrClient) ExecuteProtocol(){
    // bouncing protocol is run
}
```
All we had to do to start emmy client then is to pick appropriate implementation at the very beginning. So example would be started like this:
```go
func PickClient(schemaName string) Client{
    switch schemaName{
    case "pedersen":
        return &PedersenClient{}
    case "schnorr":
        return &SchnorrClient{}
    }
}

client := PickClient(schemaName)
client.ExecuteProtocol()
```
*Notice how `PickClient()` return type is the interface. This means that your program, from this point on, does not care what implementation is underneath.*

The nice thing, should we decide to go with such an approach, would be that emmy program doesnt even notice if we implement yet another scheme. In other words, to support a new scheme, we only need to provide another interface implementation and update the `PickClient()` function with additional case. All other parts of the program would remain untouched!

# Impact
I believe this may feel like reimplementing the whole program, but that's not true. I think we would quite enjoy to first implement e.g. Pedersen knowing that the other four schemas will come at no cost.

@mancabizjak @miha-stopar What do you think?

**Comment by miha-stopar** [comment]
I agree. However, there are (will) be schemes with more than one protocol. For example pseudonym system has the following four protocols:

RegisterWithCA (register with a trusted third party)
GenerateNym (register with an organization which can issue or accept a credential)
IssueCredential (organization issues a credential)
CredentialTransfer (organization verifies a credential)

The main goal of the library is to provide a simple API to execute these protocols. That would mean something like:

client = PseudonymSysClient(...)
client.RegisterWithCA(...)
client.GenerateNym(...)
client.IssueCredential(...)
client.CredentialTransfer(...)

Note that these four protocols are not subprotocols of one protocol - they might be executed at different times (actually, client.CredentialTransfer is executed every time the client wants to anonymously authenticate to the organization).

Each of these functions, for example RegisterWithCA, will execute some protocol, like Schnorr. So it will instantiate a SchnorrProver and then run Schnorr. However, the messages exchanged can be slightly extended in comparison to the ones used in a simple Schnorr. That means we cannot simply use SchnorrProverClient, we need to define new grpc messages, use SchnorrProver and convert messages between SchnorrProver outputs and grpc messages. RegisterWithCA would then look something like:

RegisterWithCA(...)
	schnorrProver = dlogproofs.NewSchnorrProver(...)
	x = schnorrProver.GetProofRandomData(...)
	prepare grpc message which would contain x and some additional data, like nym.A, nym.B
	send grpc message to the CA
	receive challenge
	schnorrProver.GetProofData(challenge)
	...
	
For primitives like SchnorrProver, it should be similar - it should enable API like:

client = SchnorrProverClient(...)
challenge = client.ProofRandomData(...)
client.ProofData(proof_computed_from_challenge)

Here indeed I would put the interaction (ProofRandomData, ProofData) into a method named ExecuteProtocol (to be able to execute client.ExecuteProtocol). However, this is pretty much only for demonstration purposes since Schnorr messages in more complex schemes will vary from scheme to scheme and SchnorrProverClient won't be actually needed there (only SchnorrProver with some customized messages).

**Comment by mancabizjak** [comment]
@miha-plesko your suggested approach would also remove the need for naming functions with essentially the same functionality differently. For instance, the CSPaillier and CSPaillier EC protocols both require opening step, but this step is slightly different between the two, which calls for either:
1.  not-so-convenient "general `open` function" with a lot of branching (this is how we do it for Pedersen and Pedersen EC scheme, but it's not very readable), or
2. naming of the functions like `openEC` for CSPaillier EC as opposed to `open` for CSPaillier (this is how we currently do it).

So from this point of view, making `Client` an `interface{}` and then creating structs that implement this interface + possibly hooking these new structs  (like `CSPaillierClient` and `CSPaillierECClient`) to helper functions (for instance `(c *CSPaillierClient) open()` and `(c *CSPaillierECClient) open()`) would be much cleaner in my opinion.

@miha-stopar If we do this refactoring as suggested, I don't think it will introduce any trouble with implementing multi-protocol schemas like the pseudonym system, or make it harder for users of emmy to use its functionality. Here's an example which we can follow to add/modify relevant interfaces and structs for the case of pseudonym system.

```go
type Client interface() {
	ExecuteProtocol() // does the gRPC stuff (ping-pong between client and server)
}

// this struct will hold data that is currently in the Client struct
type CommonClient struct {
	id 	int32
	conn    *grpc.ClientConn
	client  pb.ProtocolClient
	stream  pb.Protocol_RunClient
}
// We would hook common operations to this CommonClient struct in order not to duplicate 
// this in structs implementing the Client interface
(c *CommonClient) send() {...}
(c *CommonClient) recieve() {...}

// Here's how a new SchnorrClient would look after refactoring.
// We would embed the CommonClient and give it data currently
// passed to client via Schnorr function.
type SchnorrClient struct {
	protocolType common.ProtocolType,
	dlog *dlog.ZpDLog,
	secret *big.Int
	CommonClient // allows calling send and recieve directly on SchnorrClients
// Communication logic currently in Schnorr() would be moved here
(c *SchnorrClient) ExecuteProtocol() {...}

// We would do similar for all other protocols
type CARegistrationClient struct {
	CommonClient
	// + additional fields, if required
} 
(c *CARegistrationClient) ExecuteProtocol() {...}

type NymGenerationClient struct {
        CommonClient
	// + additional fields, if required
} 
(c *NymGenerationClient) ExecuteProtocol() {...}
```
We would define `CredentialIssueClient` and `CredentialTransferClient` in a similar fashion. Then, we would do something like this for the definiton of pseudonym system:

```go
type PseudonymSystem struct {
	regClient CARegistrationClient,
	nymGenClient NymGenerationClient,
	credIssueClient CredentialIssueClient,
	credTransferClient CredentialTransferClient
	// other fields, if required
}
(pseudoSys *PseudonymSystem) NewPseudonymSystem(...) *PseudonymSystem {...}

(pseudoSys *PseudonymSystem) register(...) {
	pseudoSys.regClient.ExecuteProtocol()
}
(pseudoSys *PseudonymSystem) generateNym(...) {
	pseudoSys.nymGenClient.ExecuteProtocol()
}
// similar for `(pseudoSys *PseudonymSystem) issueCredentials` and
// `(pseudoSys *PseudonymSystem) transferCredentials` functions, omitting here.
```

The programmer will then use it like this:

```go
ps := NewPseudonymSystem(...)
ps.register(...)
ps.generateNym(...)
ps.issueCredentials(...)
ps.transferCredentials(...)
```
which seems appropriate, right? The end user need not worry about how the clients structs are implemented if we define the structs like this.

Is this reasonable? What do you think?

**Comment by miha-plesko** [comment]
@miha-stopar I see your problem, some clients can not be described as *a blackbox that you fill data in and invoke `ExecuteProtocol()` on it*. At the moment I can think of two possible solutions:

### a) Parametrize ExecuteProtocol() function
By "parametrize" I mean "introduce `protocolName` argumet". Something like:
```go
type Client interface {
    ExecuteProtocol(protocolName string)
}

type PseudonymSystemClient struct { }

func (c *PseudonymSystemClient) ExecuteProtocol(protocolName string){
    switch protocolName{
    case "register-with-ca":
        c.RegisterWithCA()
    case "generate-nym":
        c.GenerateNym()
    ...
    }
}
```
User would use it simply as:
```go
client := PickClient("pseudonym", payload) // returns interface implementation
// --- from here on we don't care what client implementation we have, we just need to know protocol name
client.ExecuteProtocol("register-with-ca")
client.ExecuteProtocol("generate-nym")
```
I think this solution would be quite good from user's perspective, but it relies heavily on the fact that user will never need specific result being returned from `ExecuteProtocol(protocolName)` function (otherwise user would have to type-cast it, which is really bad UX).

Q: Is this the case? In other words, should any of the functions that you've listed (RegisterWithCA, GenerateNym, IssueCredential, CredentialTransfer) return some value that user needs to capture?

### b) Don't use interface, but only structs
The second solution is basically what @mancabizjak suggests - that we yes, encapsulate things into struct, but not interfaced one:
```go
type PseudonymSystemClient struct { }

func (c *PseudonymSystemClient) RegisterWithCA(){ ... }
func (c *PseudonymSystemClient) GenerateNym(){ ... }
func (c *PseudonymSystemClient) IssueCredential(){ ... }
func (c *PseudonymSystemClient) CredentialTransfer(){ ... }
```
User would use it simply as:
```go
client := PseudonymSystemClient(payload)
// --- everything from here on changes if we use another client than PseudonymSystemClient
client.RegisterWithCA()
client.GenerateNym()
...
```

I'm looking forward to further discussion on this. In fact, I'm quite curious what the actual solution will be :smile:

**Comment by miha-stopar** [comment]
@mancabizjak I was not against the approach, but just needed to point out how the API should look like. I like what you proposed.
@miha-plesko there are different inputs and outputs, for example the output of RegisterWithCA is the input for GenerateNym. I think your b) is what we all agree upon.

**Comment by miha-plesko** [comment]
b) sounds reasonable for me 👍

**Comment by mancabizjak** [comment]
Great, lets go for the option b) then. I will submit a PR when the clients are refactored accordingly. Thank you both for the feedback!
