### ISSUE TITLE
Flutter client

### ISSUE THREAD

**Issue by gedw99** [xlab-si/emmy#86]
I am building a client.

Should it keep the keys in a secure storage on the OS ? I ask because I am not sure of the mechanisms being used crytographically

**Comment by mancabizjak** [comment]
Hi @gedw99. The short answer is *yes*. 

You should always keep secret cryptographic material (in particular private keys, pseudonyms, credentials) as safe as possible. It's also a good idea to encrypt secret crypto material prior to storing it as an additional layer of security, but whether this is suitable/needed at all depends on the  workflow of your application as well as implementation of the underlying OS's secure storage.

I hope this answers your question :slightly_smiling_face:

**Comment by gedw99** [comment]
its does. I just wanted to check because this crypto approach is really new to me.
